// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/Stymphalian/ikuaki/api/protosfat/fattyghost.proto

/*
Package Stymphalian_ikuaki_api_protosfat is a generated protocol buffer package.

It is generated from these files:
	github.com/Stymphalian/ikuaki/api/protosfat/fattyghost.proto

It has these top-level messages:
	Fat
	Skinny
*/
package Stymphalian_ikuaki_api_protosfat

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Fat struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *Fat) Reset()                    { *m = Fat{} }
func (m *Fat) String() string            { return proto.CompactTextString(m) }
func (*Fat) ProtoMessage()               {}
func (*Fat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Fat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Skinny struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Last string `protobuf:"bytes,2,opt,name=last" json:"last,omitempty"`
}

func (m *Skinny) Reset()                    { *m = Skinny{} }
func (m *Skinny) String() string            { return proto.CompactTextString(m) }
func (*Skinny) ProtoMessage()               {}
func (*Skinny) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Skinny) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Skinny) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func init() {
	proto.RegisterType((*Fat)(nil), "Stymphalian.ikuaki.api.protosfat.Fat")
	proto.RegisterType((*Skinny)(nil), "Stymphalian.ikuaki.api.protosfat.Skinny")
}

func init() {
	proto.RegisterFile("github.com/Stymphalian/ikuaki/api/protosfat/fattyghost.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x0f, 0x2e, 0xa9, 0xcc, 0x2d, 0xc8, 0x48, 0xcc, 0xc9,
	0x4c, 0xcc, 0xd3, 0xcf, 0xcc, 0x2e, 0x4d, 0xcc, 0xce, 0xd4, 0x4f, 0x2c, 0xc8, 0xd4, 0x2f, 0x28,
	0xca, 0x2f, 0xc9, 0x2f, 0x4e, 0x4b, 0x2c, 0xd1, 0x4f, 0x4b, 0x2c, 0x29, 0xa9, 0x4c, 0xcf, 0xc8,
	0x2f, 0x2e, 0xd1, 0x03, 0x0b, 0x0a, 0x29, 0x20, 0x69, 0xd1, 0x83, 0x68, 0xd1, 0x4b, 0x2c, 0xc8,
	0xd4, 0x83, 0x6b, 0x51, 0x92, 0xe4, 0x62, 0x76, 0x4b, 0x2c, 0x11, 0x12, 0xe2, 0x62, 0xc9, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x0c, 0xb8, 0xd8, 0x82,
	0xb3, 0x33, 0xf3, 0xf2, 0x2a, 0xb1, 0xc9, 0x82, 0xc4, 0x72, 0x12, 0x8b, 0x4b, 0x24, 0x98, 0x20,
	0x62, 0x20, 0xb6, 0x93, 0x5f, 0x94, 0x0f, 0x09, 0xce, 0xb5, 0x26, 0xe4, 0xb8, 0x24, 0x36, 0x30,
	0xd3, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x85, 0x79, 0x61, 0x05, 0x01, 0x00, 0x00,
}
