apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ikuaki-lobby
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ikuaki
        role: lobby
        tier: backend
    spec:
      containers:
      - name: ikuaki-lobby
        image: stymphalian/ikuaki-lobby:v1
        ports:
          - containerPort: 8082
        command: ["/main"]
        args: ["--port=8082"]
---
apiVersion: v1
kind: Service
metadata:
  name: ikuaki-lobby
  labels:
    app: ikuaki
    role: lobby
    tier: backend
spec:
  type: NodePort  
  ports:
  - name: lobby
    port: 8082
  selector:
    app: ikuaki
    role: lobby
    tier: backend
        