kind: PersistentVolume
apiVersion: v1
metadata:
  name: ikuaki-redis-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/localkube/github.com/Stymphalian/ikuaki"
