// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ikuaki.proto

/*
Package ikuaki is a generated protocol buffer package.

It is generated from these files:
	ikuaki.proto

It has these top-level messages:
	AgentId
	Empty
	EnterReq
	EnterRes
	ExitReq
	ExitRes
	InformReq
	InformRes
	UpdateRes
	UpdateReq
*/
package ikuaki

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AgentId struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *AgentId) Reset()                    { *m = AgentId{} }
func (m *AgentId) String() string            { return proto.CompactTextString(m) }
func (*AgentId) ProtoMessage()               {}
func (*AgentId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AgentId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type EnterReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *EnterReq) Reset()                    { *m = EnterReq{} }
func (m *EnterReq) String() string            { return proto.CompactTextString(m) }
func (*EnterReq) ProtoMessage()               {}
func (*EnterReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *EnterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type EnterRes struct {
}

func (m *EnterRes) Reset()                    { *m = EnterRes{} }
func (m *EnterRes) String() string            { return proto.CompactTextString(m) }
func (*EnterRes) ProtoMessage()               {}
func (*EnterRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ExitReq struct {
}

func (m *ExitReq) Reset()                    { *m = ExitReq{} }
func (m *ExitReq) String() string            { return proto.CompactTextString(m) }
func (*ExitReq) ProtoMessage()               {}
func (*ExitReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ExitRes struct {
}

func (m *ExitRes) Reset()                    { *m = ExitRes{} }
func (m *ExitRes) String() string            { return proto.CompactTextString(m) }
func (*ExitRes) ProtoMessage()               {}
func (*ExitRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type InformReq struct {
	AgentName string `protobuf:"bytes,1,opt,name=agentName" json:"agentName,omitempty"`
	Text      string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *InformReq) Reset()                    { *m = InformReq{} }
func (m *InformReq) String() string            { return proto.CompactTextString(m) }
func (*InformReq) ProtoMessage()               {}
func (*InformReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *InformReq) GetAgentName() string {
	if m != nil {
		return m.AgentName
	}
	return ""
}

func (m *InformReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type InformRes struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *InformRes) Reset()                    { *m = InformRes{} }
func (m *InformRes) String() string            { return proto.CompactTextString(m) }
func (*InformRes) ProtoMessage()               {}
func (*InformRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *InformRes) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UpdateRes struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *UpdateRes) Reset()                    { *m = UpdateRes{} }
func (m *UpdateRes) String() string            { return proto.CompactTextString(m) }
func (*UpdateRes) ProtoMessage()               {}
func (*UpdateRes) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateRes) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type UpdateReq struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
}

func (m *UpdateReq) Reset()                    { *m = UpdateReq{} }
func (m *UpdateReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()               {}
func (*UpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateReq) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func init() {
	proto.RegisterType((*AgentId)(nil), "ikuaki.AgentId")
	proto.RegisterType((*Empty)(nil), "ikuaki.Empty")
	proto.RegisterType((*EnterReq)(nil), "ikuaki.EnterReq")
	proto.RegisterType((*EnterRes)(nil), "ikuaki.EnterRes")
	proto.RegisterType((*ExitReq)(nil), "ikuaki.ExitReq")
	proto.RegisterType((*ExitRes)(nil), "ikuaki.ExitRes")
	proto.RegisterType((*InformReq)(nil), "ikuaki.InformReq")
	proto.RegisterType((*InformRes)(nil), "ikuaki.InformRes")
	proto.RegisterType((*UpdateRes)(nil), "ikuaki.UpdateRes")
	proto.RegisterType((*UpdateReq)(nil), "ikuaki.UpdateReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for World service

type WorldClient interface {
	Enter(ctx context.Context, in *EnterReq, opts ...grpc.CallOption) (*EnterRes, error)
	Exit(ctx context.Context, in *ExitReq, opts ...grpc.CallOption) (*ExitRes, error)
	Inform(ctx context.Context, opts ...grpc.CallOption) (World_InformClient, error)
}

type worldClient struct {
	cc *grpc.ClientConn
}

func NewWorldClient(cc *grpc.ClientConn) WorldClient {
	return &worldClient{cc}
}

func (c *worldClient) Enter(ctx context.Context, in *EnterReq, opts ...grpc.CallOption) (*EnterRes, error) {
	out := new(EnterRes)
	err := grpc.Invoke(ctx, "/ikuaki.World/Enter", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) Exit(ctx context.Context, in *ExitReq, opts ...grpc.CallOption) (*ExitRes, error) {
	out := new(ExitRes)
	err := grpc.Invoke(ctx, "/ikuaki.World/Exit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *worldClient) Inform(ctx context.Context, opts ...grpc.CallOption) (World_InformClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_World_serviceDesc.Streams[0], c.cc, "/ikuaki.World/Inform", opts...)
	if err != nil {
		return nil, err
	}
	x := &worldInformClient{stream}
	return x, nil
}

type World_InformClient interface {
	Send(*InformReq) error
	Recv() (*InformRes, error)
	grpc.ClientStream
}

type worldInformClient struct {
	grpc.ClientStream
}

func (x *worldInformClient) Send(m *InformReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *worldInformClient) Recv() (*InformRes, error) {
	m := new(InformRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for World service

type WorldServer interface {
	Enter(context.Context, *EnterReq) (*EnterRes, error)
	Exit(context.Context, *ExitReq) (*ExitRes, error)
	Inform(World_InformServer) error
}

func RegisterWorldServer(s *grpc.Server, srv WorldServer) {
	s.RegisterService(&_World_serviceDesc, srv)
}

func _World_Enter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).Enter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ikuaki.World/Enter",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).Enter(ctx, req.(*EnterReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_Exit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorldServer).Exit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ikuaki.World/Exit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorldServer).Exit(ctx, req.(*ExitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _World_Inform_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorldServer).Inform(&worldInformServer{stream})
}

type World_InformServer interface {
	Send(*InformRes) error
	Recv() (*InformReq, error)
	grpc.ServerStream
}

type worldInformServer struct {
	grpc.ServerStream
}

func (x *worldInformServer) Send(m *InformRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *worldInformServer) Recv() (*InformReq, error) {
	m := new(InformReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _World_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ikuaki.World",
	HandlerType: (*WorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enter",
			Handler:    _World_Enter_Handler,
		},
		{
			MethodName: "Exit",
			Handler:    _World_Exit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Inform",
			Handler:       _World_Inform_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ikuaki.proto",
}

// Client API for Agent service

type AgentClient interface {
	// information from the world server
	Update(ctx context.Context, opts ...grpc.CallOption) (Agent_UpdateClient, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Update(ctx context.Context, opts ...grpc.CallOption) (Agent_UpdateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Agent_serviceDesc.Streams[0], c.cc, "/ikuaki.Agent/Update", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentUpdateClient{stream}
	return x, nil
}

type Agent_UpdateClient interface {
	Send(*UpdateReq) error
	CloseAndRecv() (*UpdateRes, error)
	grpc.ClientStream
}

type agentUpdateClient struct {
	grpc.ClientStream
}

func (x *agentUpdateClient) Send(m *UpdateReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *agentUpdateClient) CloseAndRecv() (*UpdateRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(UpdateRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Agent service

type AgentServer interface {
	// information from the world server
	Update(Agent_UpdateServer) error
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Update_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServer).Update(&agentUpdateServer{stream})
}

type Agent_UpdateServer interface {
	SendAndClose(*UpdateRes) error
	Recv() (*UpdateReq, error)
	grpc.ServerStream
}

type agentUpdateServer struct {
	grpc.ServerStream
}

func (x *agentUpdateServer) SendAndClose(m *UpdateRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *agentUpdateServer) Recv() (*UpdateReq, error) {
	m := new(UpdateReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ikuaki.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Update",
			Handler:       _Agent_Update_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "ikuaki.proto",
}

func init() { proto.RegisterFile("ikuaki.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4d, 0x4b, 0x3b, 0x31,
	0x10, 0xc6, 0x9b, 0xa5, 0xbb, 0xfb, 0xdf, 0xe1, 0x8f, 0x2f, 0x73, 0xaa, 0x8b, 0xa8, 0xcc, 0xa9,
	0x08, 0x16, 0x59, 0xbd, 0x89, 0x07, 0x0f, 0x7b, 0xe8, 0xc5, 0xc3, 0x82, 0x78, 0x5e, 0x49, 0x94,
	0x50, 0xf7, 0x35, 0x11, 0xea, 0x37, 0xf1, 0xe3, 0x4a, 0x92, 0x36, 0xc1, 0xd6, 0x83, 0xb7, 0xc9,
	0x33, 0xcf, 0xe4, 0xe1, 0x37, 0x03, 0xff, 0xe5, 0xea, 0xa3, 0x5e, 0xc9, 0x45, 0x3f, 0x76, 0xba,
	0xc3, 0xc4, 0xbd, 0xe8, 0x04, 0xd2, 0x87, 0x37, 0xd1, 0xea, 0x25, 0xc7, 0x03, 0x88, 0x24, 0x9f,
	0xb1, 0x0b, 0x36, 0xcf, 0xaa, 0x48, 0x72, 0x4a, 0x21, 0x2e, 0x9b, 0x5e, 0x7f, 0xd2, 0x19, 0xfc,
	0x2b, 0x5b, 0x2d, 0xc6, 0x4a, 0x0c, 0x88, 0x30, 0x6d, 0xeb, 0x46, 0x6c, 0x6c, 0xb6, 0x26, 0xf0,
	0x7d, 0x45, 0x19, 0xa4, 0xe5, 0x5a, 0xea, 0x4a, 0x0c, 0xa1, 0x54, 0x74, 0x0f, 0xd9, 0xb2, 0x7d,
	0xed, 0xc6, 0xc6, 0x7c, 0x71, 0x0a, 0x59, 0x6d, 0x22, 0x1f, 0xc3, 0x3f, 0x41, 0x30, 0x01, 0x5a,
	0xac, 0xf5, 0x2c, 0x72, 0x01, 0xa6, 0xa6, 0xf3, 0x30, 0xae, 0xbc, 0x81, 0xfd, 0x34, 0x3c, 0xf5,
	0xbc, 0xd6, 0xe2, 0x0f, 0x86, 0xe1, 0x37, 0x43, 0xf1, 0xc5, 0x20, 0x7e, 0xee, 0xc6, 0x77, 0x8e,
	0x57, 0x10, 0x5b, 0x1a, 0x3c, 0x5a, 0x6c, 0x36, 0xb6, 0x85, 0xcf, 0x77, 0x15, 0x45, 0x13, 0xbc,
	0x84, 0xa9, 0xa1, 0xc4, 0x43, 0xdf, 0x73, 0xf8, 0xf9, 0x8e, 0x60, 0xbc, 0xb7, 0x90, 0x38, 0x0e,
	0x3c, 0xde, 0x36, 0xfd, 0x5a, 0xf2, 0x3d, 0x49, 0xd1, 0x64, 0xce, 0xae, 0x59, 0x71, 0x07, 0xb1,
	0x3d, 0x11, 0x16, 0x90, 0x38, 0x88, 0x30, 0xee, 0xa1, 0xf2, 0x3d, 0xc9, 0x8e, 0xbf, 0x24, 0xf6,
	0xdc, 0x37, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xd0, 0xe0, 0xae, 0xfe, 0x01, 0x00, 0x00,
}
