// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rafia.proto

/*
Package rafia is a generated protocol buffer package.

It is generated from these files:
	rafia.proto

It has these top-level messages:
	Empty
*/
package rafia

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Empty)(nil), "rafia.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	Greet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Greet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/rafia.Greeter/Greet", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	Greet(context.Context, *Empty) (*Empty, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafia.Greeter/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Greet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rafia.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _Greeter_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rafia.proto",
}

// Client API for Fareweller service

type FarewellerClient interface {
	Farewell(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type farewellerClient struct {
	cc *grpc.ClientConn
}

func NewFarewellerClient(cc *grpc.ClientConn) FarewellerClient {
	return &farewellerClient{cc}
}

func (c *farewellerClient) Farewell(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/rafia.Fareweller/Farewell", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Fareweller service

type FarewellerServer interface {
	Farewell(context.Context, *Empty) (*Empty, error)
}

func RegisterFarewellerServer(s *grpc.Server, srv FarewellerServer) {
	s.RegisterService(&_Fareweller_serviceDesc, srv)
}

func _Fareweller_Farewell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FarewellerServer).Farewell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rafia.Fareweller/Farewell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FarewellerServer).Farewell(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Fareweller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rafia.Fareweller",
	HandlerType: (*FarewellerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Farewell",
			Handler:    _Fareweller_Farewell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rafia.proto",
}

func init() { proto.RegisterFile("rafia.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 106 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x4a, 0x4c, 0xcb,
	0x4c, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xd8, 0xb9, 0x58, 0x5d,
	0x73, 0x0b, 0x4a, 0x2a, 0x8d, 0x0c, 0xb8, 0xd8, 0xdd, 0x8b, 0x52, 0x53, 0x4b, 0x52, 0x8b, 0x84,
	0x54, 0xb9, 0x58, 0xc1, 0x4c, 0x21, 0x1e, 0x3d, 0x88, 0x0e, 0xb0, 0x0a, 0x29, 0x14, 0x9e, 0x12,
	0x83, 0x91, 0x19, 0x17, 0x97, 0x5b, 0x62, 0x51, 0x6a, 0x79, 0x6a, 0x4e, 0x4e, 0x6a, 0x91, 0x90,
	0x06, 0x17, 0x07, 0x8c, 0x87, 0x5f, 0x5f, 0x12, 0x1b, 0xd8, 0x01, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0x38, 0x59, 0xdc, 0x8f, 0x00, 0x00, 0x00,
}
